### PR TITLE
Update hackclub.com.yaml

### PR DESCRIPTION
**Pull request by malakar-soham**
Added flhs

### CODE REVIEW

**Review by Muirrum — CHANGES_REQUESTED** [review]
There's already an `flhs` key, you should put it there

**Review by Muirrum — APPROVED** [review]

**Comment by malakar-soham** [comment]
I think the other flhs was something else

**Comment by Muirrum** [comment]
It looks like the other flhs is google verification and mail records for G Suite

**Comment by BetsyZhang10** [comment]
I never added another flhs though.

**Comment by Muirrum** [comment]
It was probably bank, setting up your email

**Comment by malakar-soham** [comment]
Oh lol, I'll rollback

**Comment by BetsyZhang10** [comment]
Oh. So what do I do?

**Comment by BetsyZhang10** [comment]
My google workspace is also flhs.hackclub.com. Would that be one of the problems?

**Review by sampoder — CHANGES_REQUESTED** [review]
should only be one flhs

**Comment by malakar-soham** [comment]
but then builds are not passing

**Comment by BetsyZhang10** [comment]
I think the checks did pass. I see them passed on my end. 
image

**Comment by malakar-soham** [comment]
Yeah its passing now with 2 entries, but with a single entry the builds fail

**Pull request closed without merging**
