### PR TITLE
Use GitHub actions instead of circleci

### PR DESCRIPTION
**Pull request by Matt-Gleich**
Right now the jobs are failing. This is because the DNSIMPLE_ACOUNT_NUMBER isn't stored as a secret.

How to store a secret:
https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

### CODE REVIEW

**Comment by lachlanjc** [comment]
Thank you!! @maxwofford Could you take a look at this?

**Comment by maxwofford** [comment]
@Matt-Gleich Awesome! I'd love to use Github Actions.

We have secrets turned off for non-staff PRs because we didn't want someone submitting a malicious PR to leak the secrets. Is there an easy way to avoid that issue?

**Comment by Matt-Gleich** [comment]
Anyone with collaborator access to this repository can use secrets in a workflow

**Comment by maxwofford** [comment]
@Matt-Gleich Looks like this died in a dry run despite the secret being set:
Screenshot 2020-07-08 13 02 22
Screenshot 2020-07-08 13 03 05

Know what's up with this?

**Comment by Matt-Gleich** [comment]
Try this:

deploy.test:
```yaml
name: deploy

on:
  push:
    branches:
      - master

env:
  DNSIMPLE_ACCOUNT_NUMBER: ${{ secrets.DNSIMPLE_ACCOUNT_NUMBER }}

jobs:
  octodns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '2.7'
      - name: Install OctoDNS
        run: pip install octodns
        env:
          DNSIMPLE_ACCOUNT_NUMBER: ${{ secrets.DNSIMPLE_ACCOUNT_NUMBER }}
      - name: Sync w/ production DNS providers
        run: ./bin/sync
```

test.yml:
```yaml
name: test

on: ['push', 'pull_request']

env:
  DNSIMPLE_ACCOUNT_NUMBER: ${{ secrets.DNSIMPLE_ACCOUNT_NUMBER }}

jobs:
  octodns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '2.7'
      - name: Install OctoDNS
        run: pip install octodns
      - name: Do a dry run
        run: ./bin/dry-run
```

**Comment by maxwofford** [comment]
Hmmm, running into same issue. Just granted you contributor access so you can test the yaml configs yourself

**Comment by Matt-Gleich** [comment]
Did you just set it as an environment variable in circleci?

**Comment by maxwofford** [comment]
It's been an env var in circle ci since we started using circle ci. I added it as a GitHub secret earlier today (you should have access in the repo settings)

**Comment by Matt-Gleich** [comment]
Fixed!
https://github.com/hackclub/dns/actions/runs/162257761
https://github.com/hackclub/dns/actions/runs/162257761

**Pull request merged**
