### PR TITLE
Nigerian Domain

### PR DESCRIPTION
**Pull request by Abubakarharuna10**
Domain request!

### CODE REVIEW

**Comment by sampoder** [comment]
They need to be in alphabetical order :)

**Review by lachlanjc — CHANGES_REQUESTED** [review]
In reverse order of importance:
- You need to outdent your new lines
- Remove the `.hackclub.com` part—otherwise you’ll have `nigeria.hackclub.com.hackclub.com` as the domain :)
- The file must be alphabetical, so your new lines should be in the N section
- Vercel doesn’t allow setting DNS to an alias—you need the value to be `cname.vercel-dns.com`
- You unfortunately can’t use Vercel for hosting unless the project is under our Vercel account. If you’d like to still use Vercel, we’d be happy for you to transfer the repo into the `hackclub` org on GitHub & we can have it autodeploy under our account. Lmk. Otherwise, you’ll have to use an alternative hosting source like Netlify.

**Comment by Abubakarharuna10** [comment]
> In reverse order of importance:
> 
>     * You need to outdent your new lines
> 
>     * Remove the `.hackclub.com` part—otherwise you’ll have `nigeria.hackclub.com.hackclub.com` as the domain :)
> 
>     * The file must be alphabetical, so your new lines should be in the N section
> 
>     * Vercel doesn’t allow setting DNS to an alias—you need the value to be `cname.vercel-dns.com`
> 
>     * You unfortunately can’t use Vercel for hosting unless the project is under our Vercel account. If you’d like to still use Vercel, we’d be happy for you to transfer the repo into the `hackclub` org on GitHub & we can have it autodeploy under our account. Lmk. Otherwise, you’ll have to use an alternative hosting source like Netlify.

**Comment by Abubakarharuna10** [comment]
Hi lachlanjc <https://hackclub.slack.com/team/U3XP4M6AZ>
hope you are doing well
I receive the update on GitHub but how can I transfer the repo into the
hackclub org on GitHub?Thank you!
Best Regards

**Pull request closed without merging**
