### PR TITLE
Create ctrl-api.hackclub.com

### PR DESCRIPTION
**Pull request by edvilme**
For use with our API 
[https://ctrl-alt-tec-api.herokuapp.com](https://ctrl-alt-tec-api.herokuapp.com)

### CODE REVIEW

**Comment by edvilme** [comment]
Help! Test says python version is outdated 😟

**Comment by sampoder** [comment]
View my PR to your repo

**Comment by edvilme** [comment]
@sampoder Wow! Thanks a lot! It worked :D

**Review by sampoder — APPROVED** [review]
Thanks!

**Pull request merged**
