### PR TITLE
Attempt to re-add TXT record from #1343

### PR DESCRIPTION
**Pull request by maxwofford**
See https://github.com/hackclub/dns/pull/1347

### CODE REVIEW

**Comment by maxwofford** [comment]
Screenshot 2024-10-10 at 10 47 41 PM

Ah, interesting! @Dragon863: you might have already run into this, but it looks like the CNAME can't work with the TXT record. I'll try removing the CNAME record altogether.

**Comment by maxwofford** [comment]
Ok, trying to add the CNAME value back in using ALIAS records– your A record expects an IP address, but ALIAS can take a domain.

**Comment by maxwofford** [comment]
I'm merging this and checking the production build– will revert if this breaks anything!

**Comment by maxwofford** [comment]
That didn't work!
Screenshot 2024-10-10 at 10 54 28 PM
Screenshot 2024-10-10 at 10 54 28 PM

**Comment by Dragon863** [comment]
Sorry about the mess that caused. Is there any other way I could get the domain verified with nest, maybe without adding a txt record?

**Comment by DaInfLoop** [comment]
Perhaps adding the A and AAAA records manually would work?

From the Nest wiki:
```
Set your A record to 37.27.51.34 and AAAA record to 2a01:4f9:3081:399c::4.
```

**Comment by Dragon863** [comment]
> Perhaps adding the A and AAAA records manually would work?
> 
> From the Nest wiki:
> 
> > Set your A record to `37.27.51.34` and AAAA record to `2a01:4f9:3081:399c::4`.

Should I open a new PR for this?

**Pull request merged**
