### PR TITLE
stemegypt.hackclub.com

### PR DESCRIPTION
**Pull request by Mohanad-Elagan**
Let's add a contributing file, so we can work better, together!

### CODE REVIEW

**Comment by kunalbotla** [comment]
hi! can you revise the title and pr description to reflect the changes being made in this pr?

**Comment by Mohanad-Elagan** [comment]
I need to get a domain from "mohanad-elagan.github.io/STEM-Egypt-Hack-Club-Website" to "stemegypt.hackclub.com"

**Comment by Mohanad-Elagan** [comment]
Changes are done.

**Comment by kunalbotla** [comment]
looks good!

**Pull request merged**
