### PR TITLE
Adding spend.dino.icu

### PR DESCRIPTION
**Pull request by polypixeldev**
# Adding spend.dino.icu

## Description

This subdomain will be used to point to my new project, Spend Hack Club HQ's Money! It is hosted on Vercel.

### CODE REVIEW

**Review by Muirrum — APPROVED** [review]
lgtm

**Review by Muirrum — CHANGES_REQUESTED** [review]
Wait, if it's hosted on vercel shouldn't it point to `cname.vercel-dns.com.`?

**Comment by polypixeldev** [comment]
When I tried to add the domain in Vercel, this (adding A record) was what it told me to do

**Review by reesericci — APPROVED** [review]
LGTM

**Pull request merged**
