### PR TITLE
Add MX record to tilde.hackclub.com

### PR DESCRIPTION
**Pull request by CodeLongAndProsper90**
Add MX record for mail exchange

### CODE REVIEW

**Comment by cole-wilson** [comment]
@CodeLongAndProsper90 the problem you might be having is that MX records can’t be in the same zone as CNAME records. You have to replace the CNAME with an A record I think

**Comment by cole-wilson** [comment]
Same thing happened to me

**Comment by CodeLongAndProsper90** [comment]
Okay so now the MX is under mail.tilde.hackclub.com

**Comment by CodeLongAndProsper90** [comment]
Sorry, this is a weird morning

**Review by sampoder — APPROVED** [review]

**Pull request merged**
