### PR TITLE
Added shop.gaynormccown.hackclub.com

### PR DESCRIPTION
**Pull request by alialiwa2005**

### CODE REVIEW

**Review by alialiwa2005 — COMMENTED** [review]
Verified ImprovMX for gaynormccown.hackclub.com.

**Comment by alialiwa2005** [comment]
Removed ImprovMX from gaynormccown.hackclub.com

**Comment by alialiwa2005** [comment]
Added ImprovMX MX records to gaynormccown.hackclub.com successfully.

**Comment by maxwofford** [comment]
@alialiwa2005 This deploy failed, so I'm going to revert it while debugging what happened. No need to submit another PR-- I'll get these changes brought back into the repo once I figure out what happened.

**Comment by alialiwa2005** [comment]
@maxwofford Okay. No problem, take your time.

**Pull request merged**
