### PR TITLE
Add the Podcast Site

### PR DESCRIPTION
**Pull request by IamTregsthedev**
cc @zfogg

### CODE REVIEW

**Comment by zfogg** [comment]
hey you have a typo in the yaml. please fix it so the tests pass

**Comment by IamTregsthedev** [comment]
what's the typo?

**Comment by aaditgupta21** [comment]
Needs to be alphabetical order

**Comment by IamTregsthedev** [comment]
wait what about now?

**Comment by l3gacyb3ta** [comment]
Maybe down to sub-letter level

**Comment by IamTregsthedev** [comment]
I'm so confused for some reason

**Comment by IamTregsthedev** [comment]
now?

**Comment by IamTregsthedev** [comment]
nope

**Comment by l3gacyb3ta** [comment]
Seems to be good!

**Comment by IamTregsthedev** [comment]
@zfogg done, and check has passed!

**Pull request merged**
