### PR TITLE
Create stickers subdomain for discord-stickers.netlify.app

### PR DESCRIPTION
**Pull request by lem6ns**
👍

### CODE REVIEW

**Review by eilla1 — APPROVED** [review]
Stickersssssssss yay

**Review by eilla1 — CHANGES_REQUESTED** [review]
Ah it's not in alphabetical order. Could you fix that please?

**Review by eilla1 — APPROVED** [review]
lgtm!
also, are you on the [Hack Club Slack](https://hackclub.com/slack)? asking cause i don't seem to recognize you :P

**Comment by lem6ns** [comment]
> 
> 
> lgtm! also, are you on the [Hack Club Slack](https://hackclub.com/slack)? asking cause i don't seem to recognize you :P

Nope, but joined it right now.

**Review by sampoder — APPROVED** [review]
stickers!

**Comment by sampoder** [comment]
@eilla1 @kunalbotla it's really nice to be seeing dino.icu being used already a fair bit :D

**Comment by lem6ns** [comment]
Hm, subdomain doesn't seem to be working. Would I have to wait a few hours?

**Comment by eilla1** [comment]
According to [Netlify docs](https://docs.netlify.com/domains-https/custom-domains/configure-external-dns/):
>  It may take a full day for the settings to propagate across the global Domain Name System.

**Pull request merged**
