### PR TITLE
Adding dessert.hackclub.com

### PR DESCRIPTION
**Pull request by scooterthedev**
# Adding dessert.hackclub.com

## Description

Adding the Official Dessert YSWS landing page url here. This is for our official YSWS, were you ship an Android app, and get the $25 to buy your google play dev license. Right now it's on netlify, and we want to have it have a .hackclub.com url. Thanks!

### CODE REVIEW

**Review by alx-alexpark — CHANGES_REQUESTED** [review]
1. Could you sort the record alphabetically within the file?
2. Could you have an HQ person approve this PR?

**Comment by scooterthedev** [comment]
Step one is done, and I asked someone if they could approve it! Thanks for looking it over!

**Review by qcoral — APPROVED** [review]
i approve

**Review by alx-alexpark — APPROVED** [review]
Thanks, lgtm!

**Pull request merged**
