### PR TITLE
add CodetheTech

### PR DESCRIPTION
**Pull request by Shrey-Mehra**

### CODE REVIEW

**Review by sampoder — CHANGES_REQUESTED** [review]
Can you clarify the purpose of this PR?

**Comment by Shrey-Mehra** [comment]
> Can you clarify the purpose of this PR?

We are going to use the website to promote about our club, HackClub and it's events, and latest technology updates through ablog section.
We will also be using the same website to collaborate with other hackclubs around the globe.

**Comment by sampoder** [comment]
Please don't change the entire file - instead, just add one record.

**Comment by Shrey-Mehra** [comment]
> Please don't change the entire file - instead, just add one record.

Sam can you help me where I have to add the file

**Comment by sampoder** [comment]
Hey! You need to edit the hackclub.com YAML file but only add one record - not rewrite the whole file.

**Comment by Shrey-Mehra** [comment]
> Hey! You need to edit the hackclub.com YAML file but only add one record - not rewrite the whole file.

hey sam I make all the changes like I copy the code from hack club DNS and then add my file because I already make many wrong changes there you can check once

Thanks

**Comment by sampoder** [comment]
I would recommend starting a new PR - this branch is out of sync sadly

**Comment by Shrey-Mehra** [comment]
ok sure

**Pull request closed without merging**
