### PR TITLE
Adding `jagiellonbitbrewers.hackclub.com`

### PR DESCRIPTION
**Pull request by TheZebix**
# [Adding] `jagiellonbitbrewers.hackclub.com`

## Description

Adding subdomain for Jagiellon BitBrewers website. It will be used for posting projects and encouraging people to join our hackclub.

### CODE REVIEW

**Review by alx-alexpark — CHANGES_REQUESTED** [review]
Hi there, just reviewed your PR.

CNAME records cannot have paths, could that be changed? Otherwise, looks good.

**Comment by TheZebix** [comment]
Hello 
Maybe it can be changed but I don't know how😅. If I delete this path the website doesn't work.

**Comment by alx-alexpark** [comment]
You can follow this guide.

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain

**Comment by TheZebix** [comment]
Is it okay now?

**Review by alx-alexpark — CHANGES_REQUESTED** [review]
One last thing, please change the syntax to not use the `-` character. Make it look like the other entries.

**Review by alx-alexpark — APPROVED** [review]
Actually, it's ok.

**Pull request merged**
