### PR TITLE
Add Proton to hackclub.com.yaml

### PR DESCRIPTION
**Pull request by Techpro709**

### CODE REVIEW

**Comment by Techpro709** [comment]
Also I wanted to know if it is possible to get an email subdomain with this.

Like Protonz@proton.hackclub.com

And how that would work.

**Comment by krishstwt** [comment]
Yes its possible, you'll have to setup your own MX records though, you can do one email for free with zoho

**Comment by Techpro709** [comment]
image

Doesn't seem like i can do subdomain for somereason? Also for now can we just do the regular domain? I can update it later right?

**Comment by Techpro709** [comment]
Never Mind I got it to work.

**Comment by Techpro709** [comment]
@xkrishguptaa, can you tell me how to add the mx records?

**Pull request merged**
