### PR TITLE
Update hackclub.com.yaml (Add psn subdomain)

### PR DESCRIPTION
**Pull request by DhrumanGupta**

### CODE REVIEW

**Review by sampoder — CHANGES_REQUESTED** [review]
Vercel domains are not supported (& this isn't a valid way of configuring a Vercel custom domain anyway). Please use Netlify or other alternative hosts.

**Comment by DhrumanGupta** [comment]
There, does that work?

**Review by sampoder — APPROVED** [review]
I believe so, lets test.

**Comment by DhrumanGupta** [comment]
Does it take a while to work? It seems like it is redirecting it to netlify but the page isnt working. Is there something I change on netlify?

**Comment by DhrumanGupta** [comment]
Sorry, my mistake, works now!

**Comment by sampoder** [comment]
Glad to hear, enjoy the domain!

**Pull request merged**
