### PR TITLE
Add rhs subdomain

### PR DESCRIPTION
**Pull request by Vince7778**
This is for a website I'm making for my school's hack club.

### CODE REVIEW

**Comment by quackduck** [comment]
Nice!

**Comment by Vince7778** [comment]
By the way, the source code is here: https://github.com/Vince7778/hacksite

**Comment by quackduck** [comment]
CC: @sampoder :)

**Comment by sampoder** [comment]
```shell
octodns.record.ValidationError: Invalid record rhs.hackclub.com.
  - invalid IPv4 address "52.191.165.18."
```

**Review by sampoder — CHANGES_REQUESTED** [review]
Please see above

**Comment by Vince7778** [comment]
Oh, I thought I was supposed to include the period

**Review by sampoder — APPROVED** [review]

**Comment by quackduck** [comment]
Thanks Sam!

**Comment by sampoder** [comment]
FYI: DNS is down :0 cc: @maxwofford

**Comment by quackduck** [comment]
Hmm, it works okay for me!

**Pull request merged**
