### PR TITLE
Update rlturner.hackclub.com

### PR DESCRIPTION
**Pull request by prophetorpheus**

### CODE REVIEW

**Comment by zachlatta** [comment]
@MaxWofford, can you take a look at this? We already have turner.hackclub.com.

--
Zach Latta
Hack Club | zach@hackclub.com | Donate ( https://hackclub.com/donate )
@zachlatta ( https://twitter.com/zachlatta ) / fb ( https://facebook.com/crynix ) / web ( https://zachlatta.com ) / github ( https://github.com/zachlatta )

**Comment by MaxWofford** [comment]
Can't clubs have multiple subdomains?

**Comment by zachlatta** [comment]
Yeah, I guess so. Will leave to your discretion here.

--
Zach Latta

https://zachlatta.com ( http://zachlatta.com )
@zachlatta ( https://twitter.com/zachlatta ) / fb ( https://www.facebook.com/crynix ) / github ( https://github.com/zachlatta )

**Comment by MaxWofford** [comment]
Will reach out to them though -- the CNAME is to an IP address

**Pull request closed without merging**
