### PR TITLE
Update slack restriction URL

### PR DESCRIPTION
**Pull request by hkatzdev**
unfortunately, the api doesn't seem like repl.it very much. It works on @lukec11's server though perfectly.

### CODE REVIEW

**Comment by lukec11** [comment]
This IP is to one of the VMs on dedicated.servers.hackclub.com - should be more stable there than on my home connection

**Comment by lachlanjc** [comment]
I’m going to let someone with more context review/merge. @tmb?

**Comment by itsmingjie** [comment]
Found a brief mention over at https://github.com/github/octodns/issues/145. Merging now, but will keep an eye on status.

**Comment by itsmingjie** [comment]
Looks like it's working!

**Pull request merged**
