### PR TITLE
Adding ru.hackclub.com + Adding uk.hackclub.com

### PR DESCRIPTION
**Pull request by RussianDraco**
# Adding ru.hackclub.com
# Adding uk.hackclub.com

## Description

Adding these domains for Russian and Ukrainian versions of hackclub.com requested as per [hackclub/global](https://github.com/hackclub/global) and [this pull request](https://github.com/hackclub/global/pull/111)

### CODE REVIEW

**Review by alx-alexpark — DISMISSED** [review]
Hi! Thanks for translating! Could you place these two records alphabetically within the hackclub.com.yaml file?

**Comment by RussianDraco** [comment]
> Hi! Thanks for translating! Could you place these two records alphabetically within the hackclub.com.yaml file?

Doneruskies 👍

**Comment by Muirrum** [comment]
holding for hackclub/global#111

**Comment by RussianDraco** [comment]
> holding for hackclub/global#111

Merged 👍🏻

**Pull request merged**
