### PR TITLE
Add record hackathon.hackclub.com for vercel redirect to hackathonS.hackclub.com

### PR DESCRIPTION
**Pull request by alx-alexpark**

### CODE REVIEW

**Comment by devenjadhav** [comment]
@faisalsayed10 / @grymmy: On monday, could you please setup a redirect in vercel from hackathon.hackclub.com -> hackathons.hackclub.com. 

Thank you so much :)

**Comment by jaspermayone** [comment]
@devenjadhav I can merge this now if you want!

**Review by jaspermayone — APPROVED** [review]

**Review by Muirrum — APPROVED** [review]
lgtm!

**Comment by jaspermayone** [comment]
@alx-alexpark does this PR need to wait until Monday?

**Pull request merged**
