### PR TITLE
Adding pc.dino.icu, mcpepc.dino.icu, jaehyeon.dino.icu, mcpe-pc.dino.icu

### PR DESCRIPTION
**Pull request by MCPE-PC**
# Adding `pc.dino.icu`
# Adding `mcpepc.dino.icu`
# Adding `jaehyeon.dino.icu`
# Adding `mcpe-pc.dino.icu`

## Description

You can preview my handmade dino page [here](https://dino-icu.pages.dev).

### CODE REVIEW

**Comment by alx-alexpark** [comment]
Hi there! Could you explain the purposes/uses of these domains? Mainly because asking for 4 subdomains at once is a rare occurence

**Comment by MCPE-PC** [comment]
@alx-alexpark Hi!

1. All subdomains will show the same
1. The site will mainly serve my dino
1. It will also display a programmer quote and has a link to my website

**Comment by Muirrum** [comment]
Hey, do you need all four domains? Generally people request one domain.

**Comment by MCPE-PC** [comment]
If it matters, I'll be good to get only `pc.dino.icu`.

**Review by alx-alexpark — CHANGES_REQUESTED** [review]
Ok, please remove the other domains from the pull request then i'll be happy to merge!

**Review by alx-alexpark — APPROVED** [review]
LGTM!

**Pull request merged**
