### PR TITLE
Adding indian-hc-finder.hackclub.com

### PR DESCRIPTION
**Pull request by MohitTiwariBytes**
## Description
Hey, I created a website in which you can search for all the Indian Hackclubs around you! So i thought a hackclub subdomain would be great for it.  You can use it here https://indian-hackclubs.netlify.app

image_2024-06-30_152313081

### CODE REVIEW

**Review by Muirrum — CHANGES_REQUESTED** [review]
Looks like you're missing the actual DNS record

**Comment by MohitTiwariBytes** [comment]
So how to do it actually?

**Comment by MohitTiwariBytes** [comment]
Can you please help?

**Comment by MohitTiwariBytes** [comment]
This what i have done here

image_2024-06-30_170230414

**Comment by Muirrum** [comment]
hey! there's documentation for vercel in the README, I'd recommend taking a look there!

**Comment by Muirrum** [comment]
Following up on this

**Pull request closed without merging**
