### PR TITLE
[Updating]  `waka.hackclub.com`

### PR DESCRIPTION
**Pull request by kcoderhtml**
# [Updating] `waka.hackclub.com`

## Description

Switching over to heroku

### CODE REVIEW

**Review by alx-alexpark — APPROVED** [review]
yum

**Comment by kcoderhtml** [comment]
:Yay:

**Comment by muety** [comment]
Even though [wakapi](https://github.com/muety/wakapi)'s license doesn't strictly require it, I'd find it cool to leave a reference to the original project somewhere visibly on the page to appreciate hundreds of hours of work from it's contributors.

**Comment by kcoderhtml** [comment]
I’d be happy to add that! I stuck a forked notice on the repo page but i forgot to stick one on the main page. I’ll get that on there today!

**Pull request merged**
