### PR TITLE
Adding capsule.hackclub.com

### PR DESCRIPTION
**Pull request by thedev132**
# Adding `capsule.hackclub.com`

## Description

This is for the #time-capsule (aka The Hack Box) and the domain will be used for a map of all hackathons the time capsule has been. Here is my demo [here](https://time-capsule-map.vercel.app/)

### CODE REVIEW

**Comment by alx-alexpark** [comment]
Just a quick confirmation: have you received hq approval for this project/subdomain?

**Comment by devenjadhav** [comment]
Hi Alex! Just confirming that this is approved :)

**Review by alx-alexpark — CHANGES_REQUESTED** [review]
Hii, it appears you added the verification record, but not the actual record for the subdomain. You should add a CNAME record as the vercel website says

**Comment by thedev132** [comment]
Arc_jjtZunUlg0

It is asking for a TXT record not a CNAME as this is vercel.

**Comment by alx-alexpark** [comment]
You also need a CNAME record for the website itself, which is seperate from the verification

**Comment by alx-alexpark** [comment]
You can copy this as a template
```yaml
apocalypse:
  - ttl: 600
    type: CNAME
    value: cname.vercel-dns.com.
```

**Comment by thedev132** [comment]
Done

**Review by alx-alexpark — APPROVED** [review]
lgtm, thanks!

**Comment by thedev132** [comment]
Thank you so much Alex!

**Pull request merged**
