### PR TITLE
Add `ko.hackclub.com`

### PR DESCRIPTION
**Pull request by X3N064**
kr to ko according to ISO 639-1 of Korean

### CODE REVIEW

**Comment by reesericci** [comment]
This seems to be a major-ish change, @grymmy can you take a look at this?

**Comment by reesericci** [comment]
Syntax-wise this seems like a valid change

**Comment by X3N064** [comment]
Thanks.

**Comment by X3N064** [comment]
I already have edited /global repo.

**Comment by alx-alexpark** [comment]
Although this change is technically valid, I don't think it is necessary.
KO = Korean - The language
KR = Korea - The country

**Comment by X3N064** [comment]
yeah sure.

**Review by grymmy — CHANGES_REQUESTED** [review]
It appears to me that likely we just want this change to be additive (just add ko) vs. modifying the existing...

**Review by reesericci — APPROVED** [review]
LGTM - this requires changes on the vercel end though I would imagine

**Pull request merged**
