### PR TITLE
deleting space after codingcrew.dino.icu hosting link

### PR DESCRIPTION
**Pull request by shim-sham**
My previous pr was for adding codingcrew.dino.icu, but I've realised that the link won't work since there's a space after lustrous-ganache-dbb807.netlify.app. I apologise for the inconvenience

### CODE REVIEW

**Comment by alx-alexpark** [comment]
Are you sure? It appears to work

`dig +short codingcrew.dino.icu`
```
lustrous-ganache-dbb807.netlify.app.
44.219.53.183
54.84.236.175
```

**Comment by shim-sham** [comment]
codingcrew.dino.icu doesn't work for me, it goes to the netlify 'site not found' page. however lustrous-ganache-dbb807.netlify.app definitely leads to my site; i assumed it was the space after the full stop that caused the problem.

**Comment by alx-alexpark** [comment]
Make sure you add your custom domain to netlify. Netlify needs to know about your custom domain so it can do their setup.

**Comment by shim-sham** [comment]
When I try and add codingcrew.dino.icu, it says 'name codingcrew.dino.icu has a conflicting custom domain in another account.' What should I do?

**Comment by alx-alexpark** [comment]
Hmmmm I'm not sure. Do you want to contact netlify customer support?

**Comment by shim-sham** [comment]
Never mind! I genuinely don't know how but I just tried again and it worked this time; I didn't do anything different, it just went through and now codingcrew.dino.icu works! Thank you for your patience; I'm sort of new to this. :)

**Pull request closed without merging**
