### PR TITLE
Update Vanilla Minecraft Server IP

### PR DESCRIPTION
**Pull request by lukec11**
Updates vanilla MC server IP to use a proper server instead of digitalocean box

### CODE REVIEW

**Comment by lukec11** [comment]
not sure why it shows the update shop ip, but i don't think that that file is changing since i've merged in here

**Comment by lachlanjc** [comment]
Yeah, that looks fine. CircleCI must be passing before we can merge though

**Comment by tmb** [comment]
tests have been broken for a while afaik, merging

**Comment by lachlanjc** [comment]
No, they’re required to pass, & they passed on recent PRs. Our DNS cannot break. Though the tests here don’t seem to be failing for reasons related to the change.

@maxwofford, willing to check this out?

**Comment by maxwofford** [comment]
Yep, this is a permissions with CircleCI issue. Simple summary is that PRs currently need to be submitted by contributors/team members for tests to pass.

CircleCI's default is to not set the ENV vars for forked PRs from non-team contributors. We can opt-in to having the ENV vars set when running tests on forked PR tests, but the ENV vars include the auth key for our DNS, which is kinda important to keep secret. Not sure the best fix for this. Open to solutions & suggestions.

https://circleci.com/docs/2.0/oss/#pass-secrets-to-builds-from-forked-pull-requests

**Comment by maxwofford** [comment]
Actually, breaking out into a separate issue https://github.com/hackclub/dns/issues/229

**Pull request closed without merging**
