### PR TITLE
Verify luna.hackclub.com with vercel

### PR DESCRIPTION
**Pull request by svasudevan-coder**
Adding a value in the _vercel section so that we can verify the domain

### CODE REVIEW

**Comment by Muirrum** [comment]
please provide more details on what this PR is for

**Comment by svasudevan-coder** [comment]
I added a value in the _vercel in hackclub.com.yaml so that the domain can then be verified.

**Comment by Muirrum** [comment]
What's this domain for?

**Comment by Muirrum** [comment]
X-posting from #1240 :

> Will say the same thing I'm saying in https://github.com/hackclub/dns/pull/1242 -- official HQ sites should probably not be hosted on external github accounts

This would also put it on HQ's vercel account, negating the need for this PR.

**Review by Muirrum — CHANGES_REQUESTED** [review]
see comment

**Comment by svasudevan-coder** [comment]
It's for a days of service event we're organizing with hack club. is there anything else I can do to help with getting the domain?

**Review by Muirrum — APPROVED** [review]
lgtm

**Pull request merged**
