### PR TITLE
Update `polaroid.hackclub.com`

### PR DESCRIPTION
**Pull request by iUnstable0**
For the summit project polaroid cork bulletin board

### CODE REVIEW

**Review by reesericci — CHANGES_REQUESTED** [review]
The TTL should be set to something more sane than 1s, something say 600s (10min) or 300s (5min). That way resolvers can cache the record, and it's best practice. Otherwise your record is always expired and it creates a lot more unnecessary requests.

**Comment by iUnstable0** [comment]
oh right, done

**Comment by iUnstable0** [comment]
also theres. alot with ttl 1, should we change it all to sth like 600 or 3600?

**Comment by reesericci** [comment]
> also theres. alot with ttl 1, should we change it all to sth like 600 or 3600?

#1023

**Review by reesericci — APPROVED** [review]
LGTM!

**Pull request merged**
