### PR TITLE
Add MX record for runshaw.hackclub.com

### PR DESCRIPTION
**Pull request by Dragon863**
# Updating `runshaw.hackclub.com`

## Description

I'm adding a MX record to forward mail to my mail server for runshaw.hackclub.com. This is because in my hack club, club members cannot sign up to github with their school email addresses so I've set up a mail server to forward to their school ones

### CODE REVIEW

**Comment by alx-alexpark** [comment]
Generally, the policy is no mail on subdomains of hackclub.com, but considering this is receive only, I'll ask to see if that is possible.

**Comment by Dragon863** [comment]
Ah I didn't know that, thank you! As soon as GitHub support fixes the issue with our school emails I can stop using this solution, we just needed something quick to set up before our first session tomorrow so our members can sign up with this, then change their account email in settings

**Comment by alx-alexpark** [comment]
Hii, unfortunately we cannot allow sending or receiving mail on subdomains of hackclub.com at this time. Hopefully you can resolve your issue. Feel free to ask around on slack if you need any help.

**Comment by Dragon863** [comment]
That's a shame but thanks for checking. Would it be okay on a dino.icu subdomain?

**Pull request closed without merging**
