### PR TITLE
Updating Source Domain

### PR DESCRIPTION
**Pull request by kpanjolia**
The previous source domain was not able to connect with the subdomain. Please update this file.

### CODE REVIEW

**Review by eilla1 — CHANGES_REQUESTED** [review]
hey @kpanjolia! It didn't work before because you don't have a `CNAME` file in your repo [`ayushi-k8/hcaustin`](https://github.com/ayushi-k8/hcaustin). You can reference the [GitHub pages documentation](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages) to set that up. Also feel free to ask in the #code channel in Slack!

The CNAME that is currently on the `main` branch for austin.hackclub.com should be correct and work as intended if you set it up correctly on your end.

**Review by sampoder — APPROVED** [review]
CNAME seems to have been added, going to merge in as this config should be good

**Comment by cjdenio** [comment]
This won't work, because paths aren't part of a domain

**Comment by cjdenio** [comment]
Try making the record `ayushi-k8.github.io` instead.

**Comment by eilla1** [comment]
The record in this repo is correct. `austin` points to `ayushi-k8.github.io`. The issue is that the CNAME file in [`ayushi-k8/hcaustin`](https://github.com/ayushi-k8/hcaustin) contains "http://". Should just be `austin.hackclub.com` without the protocol.

cc @kpanjolia

**Comment by kpanjolia** [comment]
Thank you! It works now!

**Pull request merged**
