### PR TITLE
add dino.icu to production.yaml

### PR DESCRIPTION
**Pull request by kunalbotla**
oops I missed adding the domain to the `production.yaml` file

### CODE REVIEW

**Comment by eilla1** [comment]
dino.icu comes before dinosaurbbq.org alphabetically

**Review by eilla1 — CHANGES_REQUESTED** [review]
dino.icu comes before dinosaurbbq.org alphabetically

**Comment by kunalbotla** [comment]
that doesn't seem to have fixed

**Comment by eilla1** [comment]
> yaml.constructor.ConstructorError: keys out of order: expected orpheus got parker at   in "./dino.icu.yaml", line 24, column 1
86

**Comment by kunalbotla** [comment]
thank you for catching + making that change, Ella & Sam!

**Pull request merged**
