### PR TITLE
Adding hacknoel.hackclub.com

### PR DESCRIPTION
**Pull request by shyakachaste**
# Adding hacknoel.hackclub.com

## Description

Adding a subdomain , that subdomain will be used for the hackaton website called of the HackNoel

### CODE REVIEW

**Comment by alx-alexpark** [comment]
Is this an official hack club supported hackathon?

**Comment by shyakachaste** [comment]
Yes, we are youth code camp club which is supported by Hack Club and this is the second hackaton that we are going to host and this hackaton will be also sponsored by Hack club

**Review by alx-alexpark — CHANGES_REQUESTED** [review]
Hi there!

Could you move your vercel verification record to the record with all the other verifications (check readme.md)? 

Also, you are missing the Vercel CNAME record, allowing clients to resolve the IP of your site. Make sure to add it, following the instructions from vercel.

**Comment by shyakachaste** [comment]
Hi there!

I have added the Vercel verification record to the correct place with all the other verifications, as mentioned in the README. I also added the Vercel CNAME record to allow clients to find the website. Let me know if there is anything else I need to do

**Pull request closed without merging**
