### PR TITLE
fix most recent change

### PR DESCRIPTION
**Pull request by the456gamer**
I think this broke the build for all srv records, see last build log

Untested

### CODE REVIEW

**Comment by the456gamer** [comment]
I realised that it still doesn't build cause it needs to be in the top level vercel txt record

**Comment by exu3** [comment]
Thanks @the456gamer!

**Comment by the456gamer** [comment]
No worries, glad the MC server was a useful warning

**Comment by ni5arga** [comment]
Sorry! Looks like I broke it.

**Pull request merged**
