### PR TITLE
Create `wonderland-launch.hackclub.com` and update TTL for `wonderland.hackclub.com`

### PR DESCRIPTION
**Pull request by theaquarium**

### CODE REVIEW

**Review by reesericci — CHANGES_REQUESTED** [review]
The TTL is too long, it should be at least 600s or 10 minutes

**Comment by alx-alexpark** [comment]
We are in the process of transitioning to a higher TTL slowly over time.

**Comment by theaquarium** [comment]
Alright, I've set both this one and the old Wonderland one to 3600!

**Review by reesericci — APPROVED** [review]
LGTM!

**Pull request merged**
