### PR TITLE
Adding czcx.hackclub.com

### PR DESCRIPTION
**Pull request by Mpro256**
# [Adding] `czcx.[hackclub.com]`

## Description

Provide a description here of the changes, and if adding a subdomain provide a rationale & what it will be used for.
It will be used for my portfolio website to be hosted on a hackclub.com domain.

### CODE REVIEW

**Comment by leowilkin** [comment]
Hey :)

You can't use a hackclub.com domain for a personal portfolio - try using dino.icu instead!

**Review by alx-alexpark — CHANGES_REQUESTED** [review]
Please move to dino.icu

**Comment by Muirrum** [comment]
Hey! Is this still needed?

**Comment by Mpro256** [comment]
No.

**Pull request closed without merging**
