### PR TITLE
added vercel domain verification 

### PR DESCRIPTION
**Pull request by kumar-kalyan**

### CODE REVIEW

**Comment by kum9748ar** [comment]
@maxwofford can you help me to merge this

**Comment by maxwofford** [comment]
It looks like this removes the verification for `hackerabad.hackclub.com`. Did you mean to do that? If you want both, you could do something like this:
```yml
_vercel:
  ttl: 1
  type: TXT
  values: 
    - vc-domain-verify=hackerabad.hackclub.com,6c3d5d32a250935189d8
    - vc-domain-verify=hackbeats.hackclub.com,5f61f2ff84f3521a0a57
```

**Comment by maxwofford** [comment]
cc @kunalbotla – i think you were playing with multiple vercel accounts using HC domains.

**Comment by kum9748ar** [comment]
what should I do now to verify my dns

**Comment by kunalbotla** [comment]
unfortunately, you can only use vercel with dino.icu domains. you can add the same records you have to that file

**Comment by kum9748ar** [comment]
@kunalbotla  so should I host the websit on netlify will that work

**Comment by kunalbotla** [comment]
yeah that would work

**Comment by maggie-j-liu** [comment]
hi @kunalbotla and @kum9748ar! actually vercel does support multiple accounts for one domain now; i updated the readme with the instructions. i think what max put here https://github.com/hackclub/dns/pull/702#issuecomment-1148938535 is correct

**Comment by kunalbotla** [comment]
@maggie-j-liu can you link me to that? we have a custom configuration with vercel on dino.icu that allowed it, but not on the others for security reasons.

**Comment by kunalbotla** [comment]
@maggie-j-liu & @kum9748ar, that's for transferring a domain's ownership. if you were to add that record, it would remove hackclub.com from Hack Club's Vercel account. dino.icu is the domain configured as an eTLD for Vercel

**Comment by maggie-j-liu** [comment]
hii @kunalbotla i've tested this and it's not the case... it doesn't transfer the domain; it just delegates a subdomain to another account. you're able to get the subdomain back if you ever need to use it by removing the verification record

**Comment by maxwofford** [comment]
@maggie-j-liu that'd be helpful for testing! that way we can also check that removing the verification TXT record removes the subdomain from Vercel immediately.

**Comment by kum9748ar** [comment]
@maxwofford @kunalbotla @maggie-j-liu can I  get  a feedback on my last commit

**Comment by kunalbotla** [comment]
@maggie-j-liu I don't want to test this in production. let me reach out to Vercel to see if they have any information.

**Comment by kum9748ar** [comment]
Hey can I get a feedback on this

**Comment by kum9748ar** [comment]
Unable to verify domain at vercel

**Comment by sampoder** [comment]
@kumar-kalyan @maggie-j-liu @maxwofford @kunalbotla, following up on this PR. Should it be closed?

**Pull request closed without merging**
