### PR TITLE
Added A record for OrpheusHacks

### PR DESCRIPTION
**Pull request by malteianlauterbach**

### CODE REVIEW

**Comment by hkatzdev** [comment]
All records must be in alphabetical order

**Comment by Farzanfa** [comment]
yeah numberwang:
````

  ttl: 1
  type: CNAME
  value: impactdns.techby.org.

<here>

p2p:
  ttl: 1
  type: CNAME
  value: p2phack.club.

````

**Comment by malteianlauterbach** [comment]
Ah that explains why the check failed. Will fix.

Am Mo., 12. Okt. 2020 um 13:24 Uhr schrieb Farzan F A <
notifications@github.com>:

**Comment by hkatzdev** [comment]
Dupe of #399 now

**Pull request closed without merging**
