### PR TITLE
Added srv records for minecraft server

### PR DESCRIPTION
**Pull request by TheEpicProgrammer**
added 
modded-mc.hackclub.com for the modded mc server
beta-mc.hackclub.com for the experimental mc server(not always used)

### CODE REVIEW

**Comment by maxwofford** [comment]
Please fix the breaking tests-- happy to merge when it's passing.

You'll need the yaml file alphabetized

**Comment by TheEpicProgrammer** [comment]
Is that is all i need to do? are the srv records setup correctly?

**Comment by maxwofford** [comment]
Go ahead and make the change to the PR so the tests can check if the records are correct

**Comment by maxwofford** [comment]
At a glance though, it looks like you have 2 SVR records under one subdomain. Is that intentional?

**Comment by TheEpicProgrammer** [comment]
Oh i need to fix that and alphabetize it, i just woke up today

**Comment by TheEpicProgrammer** [comment]
TypeError: string indices must be integers

Idk there thou

**Comment by maxwofford** [comment]
@TheEpicProgrammer I noticed mc.hackclub.com points to the same server. Did you have that running on another port? We can add that now to prevent conflicts in the future.

**Comment by TheEpicProgrammer** [comment]
@maxwofford That is fine, mc.hackclub.com is the vanilla server and it runs on the default minecraft port

**Pull request merged**
