### PR TITLE
Add hcarc subdomain

### PR DESCRIPTION
**Pull request by faisalsayed10**

### CODE REVIEW

**Review by Muirrum — CHANGES_REQUESTED** [review]
MX and CNAME records can't coexist

**Comment by faisalsayed10** [comment]
can we remove MX?

**Comment by Muirrum** [comment]
No, we need that to continue to receive legal notices from the FCC.

**Comment by faisalsayed10** [comment]
In that case, I'm unsure what other ways there are

**Comment by Muirrum** [comment]
Vercel should provide an A record for this purpose, I just need to know what it is to complete #1186

**Review by ShubhamPatilsd — APPROVED** [review]
LGTM 🙌 🚀

**Comment by faisalsayed10** [comment]
image
i dont see anything

**Comment by mrhappyma** [comment]
https://vercel.com/guides/a-record-and-caa-with-vercel

**Comment by Muirrum** [comment]
Closing this in favor of #1186

**Pull request closed without merging**
