### PR TITLE
Add Agra Hack Club

### PR DESCRIPTION
**Pull request by CodeWithShreyans**
# Adding `agra.hackclub.com`

## Description

Adding Agra Hack Club, site custom made for upcoming Counterspell hackathon.

### CODE REVIEW

**Review by alx-alexpark — APPROVED** [review]
lgtm

**Comment by AdamEXu** [comment]
wait, we can do this???

**Comment by alx-alexpark** [comment]
Ah wait my mistake, we don't give out hackclub.com subdomains for counterspells. I confused this for another pull request which was for a club website. Please feel free to host your counterspell website on your own domain or PR into the counterspell repo.

**Comment by alx-alexpark** [comment]
I have reverted this PR. I am sorry for my mistake.

Please feel free to message me (@alex (p variant)) on slack if you need any help at all.

**Comment by CodeWithShreyans** [comment]
ah I thought since it was the current thing going on for the club it'll be fine but it's fine ig, i'll just put it on my domain

**Comment by AdamEXu** [comment]
NOOOOOOOOOO :sob:

**Comment by alx-alexpark** [comment]
@CodeWithShreyans is this a currently registered hack club?

**Comment by CodeWithShreyans** [comment]
yes

**Comment by CodeWithShreyans** [comment]
sorry for the confusion guys 😅

**Comment by alx-alexpark** [comment]
If you change your site to be a club website, it's ok to mention counterspell, but counterspell can't be the entire website.

**Pull request merged**
