### PR TITLE
Add keys.hackclub.com

### PR DESCRIPTION
**Pull request by l3gacyb3ta**

### CODE REVIEW

**Review by eilla1 — APPROVED** [review]
🔑

**Comment by eilla1** [comment]
Could you alphabetize the record please?

**Comment by l3gacyb3ta** [comment]
Ah fudge, is isnt?

**Comment by eilla1** [comment]
All good!

**Comment by l3gacyb3ta** [comment]
Wait it is.

**Comment by l3gacyb3ta** [comment]
Perfect!

**Comment by maxwofford** [comment]
Screen Shot 2022-01-25 at 16 13 32

**Pull request merged**
