### PR TITLE
Adding osca.hackclub.com

### PR DESCRIPTION
**Pull request by opott**
# Adding `osca.hackclub.com`

## Description

A website for a school Hack Club. Not much content for now, but will be improved over time!

### CODE REVIEW

**Comment by alx-alexpark** [comment]
Hey,

What is this for? It appears it is just a GitHub pages verification record. It appears there is already something on ocsa.hackclub.com, did you coordinate with them to make this change?

**Comment by opott** [comment]
Hi @alx-alexpark,
This is a completely separate Hack Club. We just have very similar names it seems!

**Comment by opott** [comment]
We are **OSCA**, they are **OCSA**.

**Comment by alx-alexpark** [comment]
Ah I see. It appears you don't have a record for the actual site itself to go with the verification record. Could you make sure to add that?

**Comment by opott** [comment]
Sorry, I've never done this before! How would I go about doing this?

**Comment by opott** [comment]
Alrighty, I'll sort that right away!

**Comment by opott** [comment]
Just pushed that change for you!

**Review by alx-alexpark — APPROVED** [review]
lgtm, sorry for the late review.

**Comment by opott** [comment]
Thank you!

**Pull request merged**
