### PR TITLE
Add atx.hackclub.com

### PR DESCRIPTION
**Pull request by reesericci**
I run a hack club at the Austin Public Library and would like apl.hackclub.com to redirect to our website (a matrix chatroom).

Thanks!

--reese

### CODE REVIEW

**Comment by kunalbotla** [comment]
this looks good, however, i want to note that DNSimple has a built-in forwarding system. you can use `URL` records to forward without any third party: https://support.dnsimple.com/articles/differences-between-a-cname-alias-url/. lmk which you prefer and i can merge!

**Comment by kunalbotla** [comment]
this looks great, @reesericci! i just want to note that DNSimple has an integrated way of forwarding URLs. you can use a `URL` record to forward without a third party integration: https://support.dnsimple.com/articles/differences-between-a-cname-alias-url/. lmk which you prefer and i can merge!

**Comment by reesericci** [comment]
ok i changed it

**Comment by kunalbotla** [comment]
hm, i'm not sure what's going on here. [all record types](https://github.com/octodns/octodns-dnsimple/#records) are supposed to be supported. @maxwofford do you know what the issue could be?

**Comment by cjdenio** [comment]
Looks like DNSimple's `URL` isn't a standard DNS record type, so octodns's core doesn't support it.

**Comment by reesericci** [comment]
Is there any course of action to resolve the issue?

**Comment by kunalbotla** [comment]
I think the best move would be to use the third-party tool you were using before. fixing this may take longer and something to change down the line.

**Comment by Benson665** [comment]
Thanks so much you are all my families

**Pull request closed without merging**
