### PR TITLE
Update mason.hackclub.com

### PR DESCRIPTION
**Pull request by prophetorpheus**

### CODE REVIEW

**Comment by lachlanjc** [comment]
@cravend @megancui Are you sure you want this live? I think it will break your subdomain

**Comment by cravend** [comment]
Wait no I did this wrong I can’t read

**Comment by cravend** [comment]
I’m trying to point it to mason-hack-club.netlify.com

**Comment by lachlanjc** [comment]
@cravend Yep, you’ll need to paste that URL directly on your Leaders dashboard

**Comment by cravend** [comment]
thanks i fixed her

**Pull request merged**
