### PR TITLE
Add bank wrapped

### PR DESCRIPTION
**Pull request by YodaLightsabr**
Bank wrapped is a work in progress, but I need to get the domain working so I can link it to bank.

### CODE REVIEW

**Comment by sampoder** [comment]
wrap-tastic! i love wraps!

**Comment by sampoder** [comment]
check out that wrap:

**Comment by sampoder** [comment]
now that's a wrap on wrap jokes! sorry you all.

**Comment by YodaLightsabr** [comment]
This is incredible.

**Pull request merged**
