### PR TITLE
Update hackclub.com.yaml

### PR DESCRIPTION
**Pull request by mrunankpawar**
Updated hackclub.com.yaml for subdomain of Hack Club TechBrewers

### CODE REVIEW

**Review by eilla1 — COMMENTED** [review]
Hi! Could you please make sure it's in alphabetical order? Everything else looks good.

**Comment by mrunankpawar** [comment]
Hey Kunal, I think you have merged the PR, do I need to make any changes
now?

**Comment by kunalbotla** [comment]
Nope! Your changes should be live soon

**Comment by mrunankpawar** [comment]
Great, thank you so much. Sorry for the trouble

**Pull request merged**
