### PR TITLE
Added New Canaan

### PR DESCRIPTION
**Pull request by geekjr**
This PR is to add a subdomain for my club.

### CODE REVIEW

**Review by exu3 — CHANGES_REQUESTED** [review]
You'll also need to add the Vercel verification record. See https://github.com/geekjr/dns/blob/c00a544201f49e4f7216090b8d20546749844b4d/hackclub.com.yaml#L228-L252

**Comment by geekjr** [comment]
Where do I get that string of characters at the end from?

**Comment by exu3** [comment]
Ah I see, this should be fine in that case.

**Review by exu3 — APPROVED** [review]

**Comment by exu3** [comment]
Up to 1-2 days, but probably sooner. 

Looks like it has propagated:

Screenshot 2023-04-06 at 12 45 21 PM

**Comment by geekjr** [comment]
Cool! Is the lag to load the page a Scrapbook issue or DNS related?

**Comment by exu3** [comment]
Not sure, as I'm not familiar with this feature. The best place to ask would be `#scrapbook-dev` on Slack.

**Pull request merged**
