### PR TITLE
Add Cullman Hack Club site (ccshc.hackclub.com)

### PR DESCRIPTION
**Pull request by FlipMods**

### CODE REVIEW

**Review by alx-alexpark — CHANGES_REQUESTED** [review]
Please increase the TTL to something higher such as 300 (5 minutes) or 3600 (1 hour).

**Comment by alx-alexpark** [comment]
Also check the subdomain name, is that a typo?

**Comment by FlipMods** [comment]
no it is not a typo lol it is how i am setting it up for now

**Comment by FlipMods** [comment]
and Is 2 minutes high enough for the TTL(Time To Live)?

**Comment by alx-alexpark** [comment]
Would prefer higher

**Comment by alx-alexpark** [comment]
> no it is not a typo lol it is how i am setting it up for now

Your github io subdomain is cmshc but the hack club subdomain is ccshc

**Comment by FlipMods** [comment]
Correct

**Comment by alx-alexpark** [comment]
Ok good, just wanted to make sure.

**Comment by FlipMods** [comment]
I Set TTL to 3 mins

**Comment by FlipMods** [comment]
Its alphabetical now

**Pull request merged**
