### PR TITLE
Add TXT record for CEC

### PR DESCRIPTION
**Pull request by Fogeinator**
This is our first time connecting a custom domain with Firebase Hosting, and I forgot to add a TXT record for it 😅
Hope things go well 👍

### CODE REVIEW

**Comment by sampoder** [comment]
Seems like GH Actions isn't very happy with Python 2, @Matt-Gleich could you help out here? Thanks!

**Comment by zachlatta** [comment]
Tests are now fixed. Now it looks like there's an error with this PR. Can you see the GitHub Action logs and fix the PR? Then we can merge.

**Comment by sampoder** [comment]
cc: @Fogeinator

**Comment by Fogeinator** [comment]
Oops, sorry was busy yesterday 😅  
I'll go see what's going on, thanks @zachlatta!!

**Comment by Fogeinator** [comment]
I think that did it - hope things go well 🤞

**Review by sampoder — APPROVED** [review]

**Pull request merged**
