### PR TITLE
Adding arson.dino.icu

### PR DESCRIPTION
**Pull request by arsoninstigator**
I will be using the subdomain as my main personal website.

### CODE REVIEW

**Review by alx-alexpark — CHANGES_REQUESTED** [review]
Hi, sorry for the late review. Could you place the subdomain in the file based on alphabetical order? `arson` starts with an `a` so it should be placed near the start of the file in its specific place.

**Comment by alx-alexpark** [comment]
And also, please add the trailing dot to your cname record so it should be `arsoninstigator.github.io.` <- (notice the dot at the end)

**Review by alx-alexpark — APPROVED** [review]
Lgtm

**Comment by arsoninstigator** [comment]
Hello,

Thanks for getting back to me. I've followed the steps and positioned the information properly in the hackclub.com.yaml file on the repo that I forked. I wanted to know if I had to create a new pull request for you to be able to see those changes or if it does that automatically. I made the changes to the main branch (in the repo I forked) and it shows that I'm 2 commits ahead of the main hc's repository.

Please let me know if there's anything else that I need to do.

Regards,
Anoushka
@arsoninstigator (screen name - anne)
________________________________

**Comment by alx-alexpark** [comment]
I saw your changes, you did everything correctly, and the subdomain has been added!

**Pull request merged**
