### PR TITLE
Add G Suite for tist.hackclub.com

### PR DESCRIPTION
**Pull request by Farzanfa**

### CODE REVIEW

**Comment by lachlanjc** [comment]
Hey! We can only merge PRs with successful checks, so take a look there for next steps.

**Comment by Farzanfa** [comment]
ohk let me check

**Comment by Farzanfa** [comment]
octodns.zone.InvalidNodeException: Invalid state, CNAME at tist.hackclub.com. cannot coexist with other records
i didnt understand this

**Comment by Farzanfa** [comment]
@lachlanjc can you please help

**Comment by Farzanfa** [comment]
i change cname record to A using 185.199.111.153 ip

**Comment by Farzanfa** [comment]
https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

**Comment by lachlanjc** [comment]
Ok great! Merging now

**Pull request merged**
