### PR TITLE
Adding italia.hackclub.com

### PR DESCRIPTION
**Pull request by Gabriele73**
Adds DNS for newly created club, Italia, based in sicily. Website is work in progress.

adds club subdomain (italia.hackclub.com) that points to 185.151.30.185 (ipv4)

### CODE REVIEW

**Comment by Gabriele73** [comment]
Updated pull request fork to include latest commit.

**Review by alx-alexpark — CHANGES_REQUESTED** [review]
Hello! Unless your club is for the entire country of Italy, I would pick a subdomain which is more specific to your club? Italia-sicily.hackclub.com would be a good choice (in my opinion)

**Comment by Gabriele73** [comment]
My bad, I thought it was possible judging by the existence of **syria.hackclub.com**.

Our club aims to open its arms to anyone who would like to join all over Italy, by Digital meetings and/or chat, although if a more specific name is required, I'll work on it.

**Comment by Gabriele73** [comment]
Referring to this pull request in the past:

https://github.com/hackclub/dns/pull/1207

As we're also based in Italy, I thought it was allowed. Let me know if I'm wrong, please.

**Review by alx-alexpark — APPROVED** [review]
> Our club aims to open its arms to anyone who would like to join all over Italy

Sounds good! It looks like you are running the only hack club in all of Italy anyway

**Comment by alx-alexpark** [comment]
FYI, I did change a bit of your record formatting, so keep that in mind for your future PRs.

**Comment by Gabriele73** [comment]
Thanks for the help, really appreciate it.

**Comment by Gabriele73** [comment]
Seems like workflow isn't running, is that normal behavior?

**Pull request merged**
