### PR TITLE
Adding `pan.hackclub.com`

### PR DESCRIPTION
**Pull request by mridun-gupta**
# Adding `pan.hackclub.com`

## Description

Required subdomain for a new locale of HackClub's website.

### CODE REVIEW

**Review by alx-alexpark — CHANGES_REQUESTED** [review]
Hi, please put the domain in the correct place in the file based on alphabetical order! 

Otherwise, everything looks good! Will hold for https://github.com/hackclub/global/pull/115

**Comment by Muirrum** [comment]
Which language is this for? don't believe `pan` is a ISO631-1 code.

**Comment by mridun-gupta** [comment]
It is for Punjabi actually.

**Comment by mridun-gupta** [comment]
@alx-alexpark I already sorted domain `pan` to it's location in `p`.

**Comment by alx-alexpark** [comment]
Hi!

I'm waiting for your pull request to be approved on the hackclub/global repository. 

As Cara said, I'm not too sure myself if `pan` is a ISO631-1 code, so I will wait for them to decide.

**Comment by mridun-gupta** [comment]
I got it.

**Comment by mridun-gupta** [comment]
Sorry, @alx-alexpark and @Muirrum, Cara was right, I made a minor issue (now, fixed), I misread the ISO631-3 code instead of the ISO631-1 code for the `Punjabi/Panjabi` language.

**Comment by Muirrum** [comment]
closing as duplicate of #1219

**Pull request closed without merging**
