### PR TITLE
Adding printalyst.hackclub.com

### PR DESCRIPTION
**Pull request by Kaympe20**
# Adding printalyst.hackclub.com

## Description

This adds the subdomain for a possible (and not at all approved) new program - Printalyst wherein, provided things like local libraries cannot, Hack Clubbers can get stuff 3d printed.

### CODE REVIEW

**Comment by alx-alexpark** [comment]
Will merge once anyone from HQ gives me the thumbs up.

**Comment by Kaympe20** [comment]
@alx-alexpark No one from HQ has seen this. I was going to use this site in my introduction to it.

**Comment by Muirrum** [comment]
this should be on dino.icu unless and until it becomes officially HQ-affiliated

**Comment by alx-alexpark** [comment]
Dino.icu is just a domain for anything

**Comment by AverseABFun** [comment]
this already exists, https://github.com/hackclub/launchpad and #printing-legion

**Comment by alx-alexpark** [comment]
@Kaympe20 Did you plan to add bakebuild?

**Comment by Kaympe20** [comment]
@alx-alexpark Working on the bakebuild site rn. How did you know about it?

**Comment by alx-alexpark** [comment]
You added a commit before closing the PR

**Pull request closed without merging**
