### PR TITLE
hack.club.hack.club

### PR DESCRIPTION
**Pull request by YodaLightsabr**

### CODE REVIEW

**Comment by reesericci** [comment]
Can I get a description on what this points to?

**Comment by YodaLightsabr** [comment]
Oh wait I did this wrong. One sec

**Comment by YodaLightsabr** [comment]
> Can I get a description on what this points to?

https://hchc.hackclub.dev

**Comment by reesericci** [comment]
> [hchc.hackclub.dev](https://hchc.hackclub.dev/)

I'm getting a 404

**Comment by YodaLightsabr** [comment]
> > [hchc.hackclub.dev](https://hchc.hackclub.dev/)
> 
> I'm getting a 404

Try adding a route such as "b" or "summit"

**Review by reesericci — APPROVED** [review]
LGTM!

**Comment by YodaLightsabr** [comment]
Enjoy [hack.club.hack.club/hack.club.hack.club/hack.club.hack.club/hack.club.hack.club](https://hack.club/hack.club/hack.club/hack.club) and [hack.club.hack.club/hack.club.hack.club/hack.club.hack.club/hack.club.hack.club](https://hack.club.hack.club/hack.club.hack.club/hack.club.hack.club/hack.club.hack.club)

**Pull request merged**
