### PR TITLE
Added thai subdomain on hackclub.com

### PR DESCRIPTION
**Pull request by toonnongaeoy**

### CODE REVIEW

**Comment by Rhenzzo** [comment]
@itsmingjie

**Comment by itsmingjie** [comment]
?

**Review by exu3 — CHANGES_REQUESTED** [review]
To host your club's website on Vercel, you'll also need to add the `_vercel` TXT record: https://github.com/hackclub/dns/blob/444d5a1f61a32cf5c42db9d930abbe60f34c3464/hackclub.com.yaml#L228-L252

**Comment by toonnongaeoy** [comment]
I don't know how to get that cause I just add this for Thai translated site on [hackclub/global](https://github.com/hackclub/globa) repository.

**Pull request merged**
