### PR TITLE
added nust.hackclub.com

### PR DESCRIPTION
**Pull request by Asim-2000**
Added Sub-Domain for Hack Club NUST.

```yaml
nust:
- ttl: 1
  type: CNAME
  value: club-website-demo2.vercel.app.
```

### CODE REVIEW

**Comment by Asim-2000** [comment]
@sampoder this is the new pull request.

**Review by sampoder — APPROVED** [review]
thank you!

**Comment by Asim-2000** [comment]
The subdomain isn't functional yet. Any specific reason for this?

**Comment by sampoder** [comment]
Vercel DNS isn't supported due to their platform limits

**Pull request merged**
